DB_LOAD_DIR = "./"
MASON = "application/vnd.mason+json"
LINK_RELATIONS_URL = "/imagenet_browser/link-relations/"
ERROR_PROFILE = "/profiles/error/"
SYNSET_PROFILE = "/profiles/synset/"
IMAGE_PROFILE = "/profiles/image/"
